import { 
    Button, 
    Center, 
    Text, 
    Flex, 
    Input, 
    InputGroup, 
    InputLeftElement, 
    Select,
    Accordion,
    AccordionButton,
    AccordionItem,
    AccordionPanel
} from "@chakra-ui/react"
import { SearchIcon } from "@chakra-ui/icons"
import FilterCars from "./FilterCars"

const Cars = () => {
    return(
        <>
        <Center
        flexDirection="column"
        gap="2rem"
        >
            <Text
            as="h1"
            fontSize="2xl"
            mt="2rem"
            fontWeight="800"
            >
                Catalogo de Autos
            </Text>
            <Flex
            justifyContent="center"
            gap="2rem"
            >
                <Button
                px="4rem"
                py="1.5rem"
                fontWeight="600"
                border="4px solid #D37301"
                borderRadius="10px"
                backgroundColor="white"
                >
                    0Km.
                </Button>
                <Button
                px="4rem"
                py="1.5rem"
                fontWeight="600"
                border="4px solid #D37301"
                borderRadius="10px"
                backgroundColor="white"
                >
                    Usados
                </Button>
            </Flex>
            <Center
            width="90%"
            gap="6rem"
            >
                <Text
                as="h3"
                fontSize="xl"
                fontWeight="800"
                >
                    Filtros
                </Text>
                <Input
                placeholder="Escribi marca, modelo, version del auto"
                />
                <Select
                width="20%"
                placeholder="Ordenar Por"
                >
                </Select>
            </Center>
            <Flex
            width="100%"
            justify="start"
            ml="6rem"
            gap="5rem"
            >
                <Flex
                direction="column"
                width="10%"
                gap="1rem"
                ml="2rem"
                >
                    <Select 
                    placeholder="Marcas"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Select 
                    placeholder="Modelos"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Select 
                    placeholder="Versiones"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Select 
                    placeholder="Transmisión"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Select 
                    placeholder="Combustibles"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Select 
                    placeholder="Segmentos"
                    fontSize="0.8rem"
                    border="none"
                    >
                        <option>
                            Volkswagen
                        </option>
                    </Select>
                    <Text as="h1" fontWeight="800">
                        Kilometraje
                    </Text>
                    <Flex
                    gap="1rem"
                    >
                        <Input
                        placeholder="Min."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                        <Input
                        placeholder="Max."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                    </Flex>
                    <Text as="h1" fontWeight="800">
                        Precio
                    </Text>
                    <Flex
                    gap="1rem"
                    >
                        <Input
                        placeholder="Min."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                        <Input
                        placeholder="Max."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                    </Flex>
                    <Text as="h1" fontWeight="800">
                        Año
                    </Text>
                    <Flex
                    gap="1rem"
                    >
                        <Input
                        placeholder="Min."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                        <Input
                        placeholder="Max."
                        fontSize="0.8rem"
                        height="2rem"
                        />
                    </Flex>
                </Flex>
                <FilterCars/>
            </Flex>
        </Center>
        </>
    )
}

export default Cars